Updated a lot of scripts

diff --git a/bin/gen_passwd b/bin/gen_passwd
--- a/bin/gen_passwd
+++ b/bin/gen_passwd
@@ -30,9 +30,17 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; exit "$1"; }
@@ -60,7 +68,7 @@ Generate passwords using /dev/urandom.
 Options:
     -h, --help           Display this help message
     -l, --length=LEN     Use specified length (default: $length)
-    --nocolor            Disable colorized output
+    --no-color           Disable colorized output
     -r, --regex=REGEX    Generate password matching specified regex
                          (default: $regex)
 
@@ -84,7 +92,7 @@ while [[ $# -gt 0 ]]; do
         "--") shift && args+=("$@") && break ;;
         "-h"|"--help") help="true" ;;
         "-l"|"--length"*) length="$(long_opt "$@")" || shift ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-r"|"--regex"*) regex="$(long_opt "$@")" || shift ;;
         *) args+=("$1") ;;
     esac
diff --git a/bin/gen_xorg_conf b/bin/gen_xorg_conf
--- a/bin/gen_xorg_conf
+++ b/bin/gen_xorg_conf
@@ -2,9 +2,17 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; exit "$1"; }
@@ -32,7 +40,7 @@ in /etc/X11/xorg.conf.d/.
 
 Options:
     -h, --help    Display this help message
-    --nocolor     Disable colorized output
+    --no-color    Disable colorized output
 
 EOF
     exit "$1"
@@ -52,7 +60,7 @@ while [[ $# -gt 0 ]]; do
     case "$1" in
         "--") shift && args+=("$@") && break ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         *) args+=("$1") ;;
     esac
     shift
diff --git a/bin/make_wallpaper b/bin/make_wallpaper
--- a/bin/make_wallpaper
+++ b/bin/make_wallpaper
@@ -32,9 +32,17 @@
 set -o noglob
 trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 127 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 127
 }
 check_lock() {
     [[ -n $cache ]] || errx 126 "Cache is not defined"
@@ -70,7 +78,7 @@ check_resume_file() {
     fi
 }
 clean() {
-    if [[ ${1:-0} -eq 0 ]]; then
+    if [[ ${1:-0} -eq 0 ]] || [[ ${1:-0} -eq 122 ]]; then
         [[ -z $cache ]] || [[ ! -d "$cache" ]] || rm -rf "$cache"
     fi
     [[ -z $script ]] || [[ ! -f "$script" ]] || rm -f "$script"
@@ -223,7 +231,7 @@ if [[ ! -f "$dataset" ]]; then
     done; unset data
 fi
 total="$(wc -l "$dataset" | awk '{print $1}')"
-[[ $total -gt 0 ]] || errx 2 "No dataset provided"
+[[ $total -gt 0 ]] || errx 122 "No dataset provided"
 
 subinfo "$total jobs to run"
 
@@ -235,7 +243,7 @@ cat >"$script" <<EOF
 ### Helpers begin
 set -o noglob
 err() { echo -e "\r${color:+\e[31m}[!] \$*\e[0m\e[K"; }
-errx() { err "\${*:2}"; exit \$1; }
+errx() { err "\${*:2}"; exit "\$1"; }
 good() { echo -e "\r${color:+\e[32m}[+] \$*\e[0m\e[K"; }
 info() { echo -e "\r${color:+\e[37m}[*] \$*\e[0m\e[K"; }
 subinfo() { echo -e "\r${color:+\e[36m}[=] \$*\e[0m\e[K"; }
diff --git a/bin/notes b/bin/notes
--- a/bin/notes
+++ b/bin/notes
@@ -30,9 +30,17 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; exit "$1"; }
@@ -62,7 +70,7 @@ Options:
     -f, --find    Find notes matching pattern (default)
     -h, --help    Display this help message
     -n, --new     New notes using pattern as filename
-    --nocolor     Disable colorized output
+    --no-color    Disable colorized output
     -o, --open    Open notes matching pattern
 
 EOF
@@ -87,7 +95,7 @@ while [[ $# -gt 0 ]]; do
         "-f"|"--find") action="find" ;;
         "-h"|"--help") help="true" ;;
         "-n"|"--new") action="new" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-o"|"--open") action="open" ;;
         *) args+=("$1") ;;
     esac
diff --git a/bin/snap b/bin/snap
--- a/bin/snap
+++ b/bin/snap
@@ -30,9 +30,17 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; unlock; exit "$1"; }
@@ -60,10 +68,7 @@ perform_snap() {
     local previous="${2:-null}"
     local new="$3"
 
-    local h
-    local w
-    local x
-    local y
+    local h w x y
 
     # Remove any maximized attributes
     wmctrl -b remove,maximized_vert,maximized_horz -ir "$id"
@@ -276,7 +281,7 @@ while [[ $# -gt 0 ]]; do
         "-l"|"--left") snap_option="left" ;;
         "-m"|"--max") snap_option="max" ;;
         "-n"|"--min") snap_option="min" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-o"|"--offset"*) offset="$(long_opt "$@")" || shift ;;
         "-p"|"--padding"*) padding="$(long_opt "$@")" || shift ;;
         "--replay") snap_option="replay" ;;
diff --git a/bin/tmussh b/bin/tmussh
--- a/bin/tmussh
+++ b/bin/tmussh
@@ -30,9 +30,17 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; exit "$1"; }
@@ -65,7 +73,7 @@ Options:
     -h, --help           Display this help message
     -i, --interactive    Do not close connection (default: true if no
                          cmd)
-    --nocolor            Disable colorized output
+    --no-color           Disable colorized output
 
 EOF
     exit "$1"
@@ -88,6 +96,7 @@ while [[ $# -gt 0 ]]; do
         "-d"|"--delay"*) delay="$(long_opt "$@")" || shift ;;
         "-h"|"--help") help="true" ;;
         "-i"|"--interactive") interactive="true" ;;
+        "--no-color") unset color ;;
         *) args+=("$1") ;;
     esac
     shift
diff --git a/security/create_meterpreter b/security/create_meterpreter
--- a/security/create_meterpreter
+++ b/security/create_meterpreter
@@ -1,15 +1,23 @@
 #!/usr/bin/env bash
 
 ### Helpers begin
-checkdeps() {
+check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v $d) ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
@@ -19,8 +27,8 @@ long_opt() {
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
 ### Helpers end
 
 default_ip() {
@@ -29,33 +37,33 @@ default_ip() {
 }
 
 usage() {
-    echo "Usage: ${0##*/} [OPTIONS] <format> [payload options]"
-    echo
-    echo "Simplify generating a meterpreter payload"
-    echo
-    echo "Options:"
-    echo "    -h, --help         Display this help message"
-    echo "    -i, --ip=IP        Connect back to specified IP address"
-    echo "                       (default: $ip)"
-    echo "    -l, --linux        Create linux meterpreter"
-    echo "    --nocolor          Disable colorized output"
-    echo "    -p, --port=PORT    Connect back to the specified port"
-    echo "                       (default: $port)"
-    echo "    -w, --windows      Create windows meterpreter (default"
-    echo "                       behavior)"
-    echo
-    echo "Executable formats:"
-    echo "    asp, aspx, aspx-exe, dll, elf, elf-so, exe, exe-only,"
-    echo "    exe-service, exe-small, hta-psh, loop-vbs, macho, msi,"
-    echo "    msi-nouac, osx-app, psh, psh-net, psh-reflection,"
-    echo "    psh-cmd, vba, vba-exe, vba-psh, vbs, war"
-    echo
-    echo "Transform formats:"
-    echo "    bash, c, csharp, dw, dword, hex, java, js_be, js_le,"
-    echo "    num, perl, pl, powershell, ps1, py, python, raw, rb,"
-    echo "    ruby, sh, vbapplication, vbscript"
-    echo
-    exit $1
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] <format> [payload options]
+
+Simplify generating a meterpreter payload
+
+Options:
+    -h, --help         Display this help message
+    -i, --ip=IP        Connect back to specified IP address (default:
+                       $ip)
+    -l, --linux        Create linux meterpreter
+    --no-color         Disable colorized output
+    -p, --port=PORT    Connect back to the specified port (default:
+                       $port)
+    -w, --windows      Create windows meterpreter (default behavior)
+
+Executable formats:
+    asp, aspx, aspx-exe, dll, elf, elf-so, exe, exe-only, exe-service,
+    exe-small, hta-psh, loop-vbs, macho, msi, msi-nouac, osx-app, psh,
+    psh-net, psh-reflection, psh-cmd, vba, vba-exe, vba-psh, vbs, war
+
+Transform formats:
+    bash, c, csharp, dw, dword, hex, java, js_be, js_le, num, perl,
+    pl, powershell, ps1, py, python, raw, rb, ruby, sh, vbapplication,
+    vbscript
+
+EOF
+    exit "$1"
 }
 
 declare -a args deps
@@ -68,7 +76,7 @@ os="windows"
 port=4444
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -77,14 +85,14 @@ while [[ $# -gt 0 ]]; do
         "-h"|"--help") help="true" ;;
         "-i"|"--ip"*) ip="$(long_opt "$@")" || shift ;;
         "-l"|"--linux") os="linux/x86" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-p"|"--port"*) port="$(long_opt "$@")" || shift ;;
         "-w"|"--windows") os="windows" ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
 # Check for valid params
 [[ -z $help ]] || usage 0
diff --git a/security/dugtrio b/security/dugtrio
--- a/security/dugtrio
+++ b/security/dugtrio
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# A script that performs a simple ping sweep and nslookup.
+# A script that performs a simple dig for provided subnets.
 # by Miles Whittaker <mjwhitta@gmail.com>
 #
 # --------------------------------------------------------------------
@@ -29,15 +29,23 @@
 # --------------------------------------------------------------------
 
 ### Helpers begin
-checkdeps() {
+check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v $d) ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
@@ -47,32 +55,35 @@ long_opt() {
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
 ### Helpers end
 
 usage() {
-    echo "Usage: ${0##*/} [OPTIONS] <subnet1>...[subnetN]"
-    echo
-    echo "Extremely simple ping sweep that also does an nslookup."
-    echo "User should provided first 3 octets of target subnets."
-    echo
-    echo "Options:"
-    echo "    -d, --dns=IP    Use the specified DNS server"
-    echo "    -h, --help      Display this help message"
-    echo "    --nocolor       Disable colorized output"
-    echo
-    exit $1
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] <subnet1>... [subnetN]
+
+Run dig against /24 subnets. User should provide first 3 octets of the
+target subnets.
+
+Options:
+    -d, --dns=IP    Use the specified DNS server
+    -h, --help      Display this help message
+    --no-color      Disable colorized output
+    -u, --up        Use ping to only display hosts that are reachable
+
+EOF
+    exit "$1"
 }
 
 declare -a args deps
-unset dns help
+unset dns help up
 color="true"
-deps+=("nslookup")
+deps+=("dig")
 deps+=("ping")
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -80,12 +91,13 @@ while [[ $# -gt 0 ]]; do
         "--") shift && args+=("$@") && break ;;
         "-d"|"--dns"*) dns="$(long_opt "$@")" || shift ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
+        "-u"|"--up"*) up="true" ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
 # Check for valid params
 [[ -z $help ]] || usage 0
@@ -95,13 +107,15 @@ trap exit SIGINT
 
 for subnet in "$@"; do
     for ip in {1..254}; do
-        ping -c 1 -W 1 $subnet.$ip >/dev/null
-        if [[ $? -eq 0 ]]; then
-            while read name; do
-                good "$subnet.$ip  $name"
-            done < <(
-                nslookup $subnet.$ip $dns | awk '/name =/ {print $NF}'
-            )
+        if [[ -n $up ]]; then
+            ping -c 1 -W 1 $subnet.$ip >/dev/null
+            [[ $? -eq 0 ]] || continue
+            good "$subnet.$ip  $(dig +short -x $subnet.$ip $dns)"
+            continue
         fi
+
+        while read -r name; do
+            good "$subnet.$ip  $name"
+        done < <(dig +short -x $subnet.$ip $dns)
     done; unset ip
 done; unset subnet
diff --git a/security/find_VDIs b/security/find_VDIs
--- a/security/find_VDIs
+++ b/security/find_VDIs
@@ -4,9 +4,17 @@
 set -o noglob
 trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 127 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 127
 }
 check_lock() {
     [[ -n $cache ]] || errx 126 "Cache is not defined"
@@ -42,7 +50,7 @@ check_resume_file() {
     fi
 }
 clean() {
-    if [[ ${1:-0} -eq 0 ]]; then
+    if [[ ${1:-0} -eq 0 ]] || [[ ${1:-0} -eq 122 ]]; then
         [[ -z $cache ]] || [[ ! -d "$cache" ]] || rm -rf "$cache"
     fi
     [[ -z $script ]] || [[ ! -f "$script" ]] || rm -f "$script"
@@ -199,7 +207,7 @@ if [[ ! -f "$dataset" ]]; then
     done < <(cat "$@" 2>/dev/null | sort -u); unset data
 fi
 total="$(wc -l "$dataset" | awk '{print $1}')"
-[[ $total -gt 0 ]] || errx 2 "No dataset provided"
+[[ $total -gt 0 ]] || errx 122 "No dataset provided"
 
 subinfo "$total jobs to run"
 
diff --git a/security/ftp_util b/security/ftp_util
--- a/security/ftp_util
+++ b/security/ftp_util
@@ -1,15 +1,23 @@
 #!/usr/bin/env bash
 
 ### Helpers begin
-checkdeps() {
+check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v $d) ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
@@ -19,8 +27,8 @@ long_opt() {
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
 ### Helpers end
 
 ftp_delete() {
@@ -56,22 +64,24 @@ EOF
 }
 
 usage() {
-    echo "Usage: ${0##*/} [OPTIONS] <host> <user> <pass> ..."
-    echo
-    echo "FTP tool for easy scripting"
-    echo
-    echo "Options:"
-    echo "    -d, --delete    Delete file on ftp server"
-    echo "    -g, --get       Get file from ftp server"
-    echo "    -h, --help      Display this help message"
-    echo "    -u, --upload    Upload file to ftp server"
-    echo
-    echo "Examples:"
-    echo "    ftp_util --upload host user pass file wwwroot/file"
-    echo "    ftp_util --delete host user pass wwwroot/file"
-    echo "    ftp_util --get host user pass wwwroot/file"
-    echo
-    exit $1
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] <host> <user> <pass> ...
+
+FTP tool for easy scripting
+
+Options:
+    -d, --delete    Delete file on ftp server
+    -g, --get       Get file from ftp server
+    -h, --help      Display this help message
+    -u, --upload    Upload file to ftp server
+
+Examples:
+    ftp_util --upload host user pass file wwwroot/file
+    ftp_util --delete host user pass wwwroot/file
+    ftp_util --get host user pass wwwroot/file
+
+EOF
+    exit "$1"
 }
 
 declare -a args deps
@@ -80,7 +90,7 @@ color="true"
 deps+=("ftp")
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -89,12 +99,13 @@ while [[ $# -gt 0 ]]; do
         "-d"|"--delete") action="delete" ;;
         "-g"|"--get") action="get" ;;
         "-h"|"--help") help="true" ;;
+        "--no-color") unset color ;;
         "-u"|"--upload") action="upload" ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
 # Check for valid params
 [[ -z $help ]] || usage 0
diff --git a/security/fw b/security/fw
--- a/security/fw
+++ b/security/fw
@@ -30,12 +30,20 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
+errx() { err "${*:2}"; exit "$1"; }
 good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
@@ -118,7 +126,7 @@ Options:
     -c, --close=PORT    Close a previously opened port
     --clear             Clear $iptables rules
     -l, --list          List $iptables rules (default behavior)
-    --nocolor           Disable colorized output
+    --no-color          Disable colorized output
     -o, --open=PORT     Open a port
     -r, --reset         Restore default $iptables rules
 
@@ -155,7 +163,7 @@ while [[ $# -gt 0 ]]; do
             ;;
         "-h"|"--help") help="true" ;;
         "-l"|"--list") action="list" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-o"|"--open"*)
             action="open"
             port="$(long_opt "$@")" || shift
diff --git a/security/gen_passwd_entry b/security/gen_passwd_entry
--- a/security/gen_passwd_entry
+++ b/security/gen_passwd_entry
@@ -28,76 +28,87 @@
 # SOFTWARE.
 # --------------------------------------------------------------------
 
-function gen_passwd_entry() {
-    if [[ -z $(command -v makepasswd) ]]; then
-        echo "makepasswd is not installed"
-        return 3
-    fi
+### Helpers begin
+check_deps() {
+    local missing
+    for d in "${deps[@]}"; do
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
+    done; unset d
+    [[ -z $missing ]] || exit 128
+}
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
 
-    gpe_cleanup() {
-        unset arg args help noblock passwd
-        unset -f gpe_cleanup gpe_usage
-    }
+usage() {
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] <username>
 
-    gpe_usage() {
-        echo "Usage: gen_passwd_entry [OPTIONS] <username>"
-        echo
-        echo "Generate /etc/passwd entries"
-        echo
-        echo "Options:"
-        echo "    -h, --help             Display this help message"
-        echo "    -n, --noblock          Don't use blocking random"
-        echo "    -p, --passwd=PASSWD    Use specified password"
-        echo
-        gpe_cleanup
-    }
+Generate /etc/passwd entries.
 
-    declare -a args
-    unset help noblock passwd
+Options:
+    -h, --help             Display this help message
+    -n, --no-block         Use non-blocking source of random
+    --no-color             Disable colorized output
+    -p, --passwd=PASSWD    Use specified password
 
-    while [[ $# -gt 0 ]]; do
-        case "$1" in
-            "--") shift && args+=("$@") && break ;;
-            "-h"|"--help") help="true" ;;
-            "-n"|"--noblock") noblock="true" ;;
-            "-p"|"--passwd"*)
-                case "$1" in
-                    "--"*"="*)
-                        arg="${1#*=}"
-                        [[ -z $arg ]] && gpe_usage && return 1
-                        ;;
-                    *)
-                        shift; [[ $# -eq 0 ]] && gpe_usage && return 1
-                        arg="$1"
-                        ;;
-                esac
-                passwd="$arg"
-                ;;
-            *) args+=("$1") ;;
-        esac
-        shift
-    done
-    [[ -z ${args[@]} ]] || set -- "${args[@]}"
-
-    [[ -n $help ]] && gpe_usage && return 0
-    [[ $# -ne 1 ]] && gpe_usage && return 2
-    [[ -n $passwd ]] || passwd="$1"
-
-    echo -n "$1"
-    if [[ -z $noblock ]];  then
-        makepasswd --clearfrom=<(echo "$passwd") --crypt-md5 | \
-            awk '{print ":"$2":0:0:::"}'
-    else
-        makepasswd --clearfrom=<(echo "$passwd") --crypt-md5 \
-            --randomseed 1 | awk '{print ":"$2":0:0:::"}'
-    fi
-
-    gpe_cleanup
+EOF
+    exit "$1"
 }
 
-if [[ -n ${BASH_SOURCE[0]} ]]; then
-    case "$0" in
-        *"bash") ;;
-        *) gen_passwd_entry "$@" ;;
+declare -a args deps
+unset help noblock passwd
+color="true"
+deps+=("awk")
+deps+=("makepasswd")
+
+# Check for missing dependencies
+check_deps
+
+# Parse command line options
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        "--") shift && args+=("$@") && break ;;
+        "-h"|"--help") help="true" ;;
+        "-n"|"--no-block") noblock="true" ;;
+        "--no-color") unset color ;;
+        "-p"|"--passwd"*) passwd="$(long_opt "$@")" || shift ;;
+        *) args+=("$1") ;;
     esac
+    shift
+done
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
+
+# Check for valid params
+[[ -z $help ]] || usage 0
+[[ $# -eq 1 ]] || usage 1
+
+[[ -n $passwd ]] || passwd="$1"
+
+echo -n "$1"
+if [[ -z $noblock ]];  then
+    makepasswd --clearfrom=<(echo "$passwd") --crypt-md5 | \
+        awk '{print ":"$2":0:0:::"}'
+else
+    makepasswd --clearfrom=<(echo "$passwd") --crypt-md5 \
+        --randomseed 1 | awk '{print ":"$2":0:0:::"}'
 fi
diff --git a/security/ghrecon b/security/ghrecon
--- a/security/ghrecon
+++ b/security/ghrecon
@@ -29,15 +29,23 @@
 # --------------------------------------------------------------------
 
 ### Helpers begin
-checkdeps() {
+check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v $d) ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
@@ -47,27 +55,28 @@ long_opt() {
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
 ### Helpers end
 
 usage() {
-    echo "Usage: ${0##*/} [OPTIONS] github_url"
-    echo
-    echo "This tool will gather a list of repo/gists from GitHub"
-    echo
-    echo "To get a TOKEN, go to the settings page of your GitHub"
-    echo "account. Click Applications and generate a personal access"
-    echo "token."
-    echo
-    echo "Options:"
-    echo "    -a, --access=TOKEN    Use the specified access token"
-    echo "    -h, --help            Display this help message"
-    echo "    --nocolor             Disable colorized output"
-    echo "    -o, --output=FILE     Output to specified file"
-    echo "    -s, --socks=SOCKS     Use the specified socks5 proxy"
-    echo
-    exit $1
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] github_url
+
+This tool will gather a list of repo/gists from GitHub.
+
+To get a TOKEN, go to the settings page of your GitHub account. Click
+Applications and generate a personal access token.
+
+Options:
+    -a, --access=TOKEN    Use the specified access token
+    -h, --help            Display this help message
+    --no-color            Disable colorized output
+    -o, --output=FILE     Output to specified file
+    -s, --socks=SOCKS     Use the specified socks5 proxy
+
+EOF
+    exit "$1"
 }
 
 declare -a args deps
@@ -76,7 +85,7 @@ color="true"
 deps+=("curl")
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -86,14 +95,14 @@ while [[ $# -gt 0 ]]; do
             token="?access_token=$arg"
             ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-o"|"--output"*) output="$(long_opt "$@")" || shift ;;
         "-s"|"--socks"*) socks="--socks5 $(long_opt "$@")" || shift ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
 # Check for valid params
 [[ -z $help ]] || usage 0
diff --git a/security/netstatplus b/security/netstatplus
--- a/security/netstatplus
+++ b/security/netstatplus
@@ -28,89 +28,109 @@
 # SOFTWARE.
 # --------------------------------------------------------------------
 
-function netstatplus() {
-    case "$(uname -s)" in
-        "Darwin") echo "Unsupported OS!" && return 2 ;;
-    esac
-
-    for exe in column netstat; do
-        if [[ -z $(command -v $exe) ]]; then
-            echo "$exe is not installed"
-            unset exe
-            return 3
+### Helpers begin
+check_deps() {
+    local missing
+    for d in "${deps[@]}"; do
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
         fi
-    done; unset exe
+    done; unset d
+    [[ -z $missing ]] || exit 128
+}
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
 
-    netstatplus_cleanup() {
-        unset args cmd help line pid sudo username
-        unset -f netstatplus_cleanup netstatplus_usage
-    }
+usage() {
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS]
 
-    netstatplus_usage() {
-        echo "Usage: netstatplus [OPTIONS]"
-        echo
-        echo "Makes netstat output a little more readable"
-        echo
-        echo "Options:"
-        echo "    -h, --help    Display this help message"
-        echo "    -s, --sudo    Run as root"
-        echo
-        netstatplus_cleanup
-    }
+Makes netstat output a little more readable.
 
-    declare -a args
-    unset help sudo
+Options:
+    -h, --help    Display this help message
+    --no-color    Disable colorized output
+    -s, --sudo    Run as root
 
-    while [[ $# -gt 0 ]]; do
-        case "$1" in
-            "--") shift && args+=("$@") && break ;;
-            "-h"|"--help") help="true" ;;
-            "-s"|"--sudo") sudo="sudo" ;;
-            *) args+=("$1") ;;
-        esac
-        shift
-    done
-    [[ -z ${args[@]} ]] || set -- "${args[@]}"
-
-    [[ -n $help ]] && netstatplus_usage && return 0
-    [[ $# -ne 0 ]] && netstatplus_usage && return 1
-
-    while read -r line; do
-        case "$line" in
-            *"Active Internet connections"*) continue ;;
-            *"PID/Program name"*)
-                echo -n "$line" | sed -r -e "s/ Address/Address/g" \
-                    -e "s#/Program name.*##g" -e "s/ +//g"
-                echo "UserCommandLine"
-                continue
-                ;;
-        esac
-
-        echo -n "$line" | sed -r -e "s#[0-9]+/.+##g" \
-            -e "s/ +(\-)?//g"
-        case "$line" in
-            "udp"*"ESTABLISHED"*) ;;
-            "udp"*) echo -n "UNCONN" ;;
-        esac
-
-        pid="$(
-            echo "$line" | grep -Eos "[0-9]+/.*" | cut -d "/" -f 1
-        )"
-        echo -n "${pid:--}"
-
-        [[ -z $pid ]] && echo && continue
-
-        username="$(ps -o user= --pid $pid)"
-        cmd="$(ps -o cmd= --pid $pid)"
-        echo "$username$cmd"
-    done < <($sudo netstat -anptu 2>/dev/null) | column -s "" -t
-
-    netstatplus_cleanup
+EOF
+    exit "$1"
 }
 
-if [[ -n ${BASH_SOURCE[0]} ]]; then
-    case "$0" in
-        *"bash") ;;
-        *) netstatplus "$@" ;;
+declare -a args deps
+unset help sudo
+color="true"
+deps+=("column")
+deps+=("grep")
+deps+=("netstat")
+
+case "$(uname -s)" in
+    "Darwin") errx 2 "Unsupported OS!" ;;
+esac
+
+# Check for missing dependencies
+check_deps
+
+# Parse command line options
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        "--") shift && args+=("$@") && break ;;
+        "-h"|"--help") help="true" ;;
+        "--no-color") unset color ;;
+        "-s"|"--sudo") sudo="sudo" ;;
+        *) args+=("$1") ;;
     esac
-fi
+    shift
+done
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
+
+# Check for valid params
+[[ -z $help ]] || usage 0
+[[ $# -eq 0 ]] || usage 1
+
+while read -r line; do
+    case "$line" in
+        *"Active Internet connections"*) continue ;;
+        *"PID/Program name"*)
+            echo -n "$line" | sed -r -e "s/ Address/Address/g" \
+                -e "s#/Program name.*##g" -e "s/ +//g"
+            echo "UserCommandLine"
+            continue
+            ;;
+    esac
+
+    echo -n "$line" | sed -r -e "s#[0-9]+/.+##g" \
+        -e "s/ +(\-)?//g"
+    case "$line" in
+        "udp"*"ESTABLISHED"*) ;;
+        "udp"*) echo -n "UNCONN" ;;
+    esac
+
+    pid="$(
+        echo "$line" | grep -Eos "[0-9]+/.*" | cut -d "/" -f 1
+    )"
+    echo -n "${pid:--}"
+
+    [[ -z $pid ]] && echo && continue
+
+    username="$(ps -o user= --pid $pid)"
+    cmd="$(ps -o cmd= --pid $pid)"
+    echo "$username$cmd"
+done < <($sudo netstat -anptu 2>/dev/null) | column -s "" -t
diff --git a/security/pwnedpassword b/security/pwnedpassword
--- a/security/pwnedpassword
+++ b/security/pwnedpassword
@@ -30,12 +30,20 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
+errx() { err "${*:2}"; exit "$1"; }
 good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
@@ -60,7 +68,7 @@ https://api.pwnedpasswords.com
 
 Options:
     -h, --help    Display this help message
-    --nocolor     Disable colorized output
+    --no-color    Disable colorized output
 
 EOF
     exit "$1"
@@ -69,7 +77,10 @@ EOF
 declare -a args deps
 unset help
 color="true"
+deps+=("awk")
 deps+=("curl")
+deps+=("grep")
+deps+=("sed")
 deps+=("sha1sum")
 
 # Check for missing dependencies
@@ -80,7 +91,7 @@ while [[ $# -gt 0 ]]; do
     case "$1" in
         "--") shift && args+=("$@") && break ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         *) args+=("$1") ;;
     esac
     shift
diff --git a/security/reverse_shell b/security/reverse_shell
--- a/security/reverse_shell
+++ b/security/reverse_shell
@@ -1,15 +1,23 @@
 #!/usr/bin/env bash
 
 ### Helpers begin
-checkdeps() {
+check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v $d) ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
@@ -19,8 +27,8 @@ long_opt() {
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
 ### Helpers end
 
 connect() {
@@ -38,23 +46,24 @@ listen() {
 }
 
 usage() {
-    echo "Usage: ${0##*/} [OPTIONS]"
-    echo
-    echo "Create a reverse shell"
-    echo
-    echo "Options:"
-    echo "    -c, --connect      Connect to a listening reverse_shell"
-    echo "                       instance"
-    echo "    -f, --fifo=FIFO    Use the specified fifo"
-    echo "    -h, --help         Display this help message"
-    echo "    --host=HOST        Use the specified host"
-    echo "    -l, --listen       Listen for a connection from a"
-    echo "                       connecting reverse_shell instance"
-    echo "    --nc=NC            Use the specified nc binary"
-    echo "    --nocolor          Disable colorized output"
-    echo "    -p, --port=PORT    Use the specified port"
-    echo
-    exit $1
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS]
+
+Create a reverse shell
+
+Options:
+    -c, --connect      Connect to a listening reverse_shell instance
+    -f, --fifo=FIFO    Use the specified fifo
+    -h, --help         Display this help message
+    --host=HOST        Use the specified host
+    -l, --listen       Listen for a connection from a connecting
+                       reverse_shell instance
+    --nc=NC            Use the specified nc binary
+    --no-color         Disable colorized output
+    -p, --port=PORT    Use the specified port
+
+EOF
+    exit "$1"
 }
 
 declare -a args deps
@@ -69,10 +78,10 @@ elif [[ -n $(command -v ncat) ]]; then
 elif [[ -n $(command -v netcat) ]]; then
     nc="$(command -v netcat)"
 fi
-port=4444
+port="4444"
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -84,13 +93,13 @@ while [[ $# -gt 0 ]]; do
         "--host"*) host="$(long_opt "$@")" || shift ;;
         "-l"|"--listen") action="listen" ;;
         "--nc"*) nc="$(long_opt "$@")" || shift ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-p"|"--port"*) port="$(long_opt "$@")" || shift ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
 # Check for valid params
 [[ -z $help ]] || usage 0
diff --git a/security/sqlmap b/security/sqlmap
--- a/security/sqlmap
+++ b/security/sqlmap
@@ -2,9 +2,17 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; exit "$1"; }
@@ -70,7 +78,7 @@ mkdir -p "$(dirname "$cache")"
 # Clear cached sqlmap if requested
 [[ -z $clear ]] || rm -rf "$cache"
 
-# Get JD-GUI if missing
+# Get sqlmap if missing
 if [[ ! -d $cache ]]; then
     git clone https://github.com/sqlmapproject/sqlmap.git "$cache"
     [[ $? -eq 0 ]] || errx 1 "Failed to download sqlmap"
diff --git a/security/ssplus b/security/ssplus
--- a/security/ssplus
+++ b/security/ssplus
@@ -28,91 +28,109 @@
 # SOFTWARE.
 # --------------------------------------------------------------------
 
-function ssplus() {
-    case "$(uname -s)" in
-        "Darwin") echo "Unsupported OS!"; return 2 ;;
+### Helpers begin
+check_deps() {
+    local missing
+    for d in "${deps[@]}"; do
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
+    done; unset d
+    [[ -z $missing ]] || exit 128
+}
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
     esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
 
-    for exe in column ss; do
-        if [[ -z $(command -v $exe) ]]; then
-            echo "$exe is not installed"
-            unset exe
-            return 3
-        fi
-    done; unset exe
+usage() {
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS]
 
-    ssplus_cleanup() {
-        unset args cmd help line pid pids sudo username
-        unset -f ssplus_cleanup ssplus_usage
-    }
+Makes ss output a little more readable.
 
-    ssplus_usage() {
-        echo "Usage: ssplus [OPTIONS]"
-        echo
-        echo "Makes ss output a little more readable"
-        echo
-        echo "Options:"
-        echo "    -h, --help    Display this help message"
-        echo "    -s, --sudo    Run as root"
-        echo
-        ssplus_cleanup
-    }
+Options:
+    -h, --help    Display this help message
+    --no-color    Disable colorized output
+    -s, --sudo    Run as root
 
-    declare -a args
-    unset help sudo
-
-    while [[ $# -gt 0 ]]; do
-        case "$1" in
-            "--") shift && args+=("$@") && break ;;
-            "-h"|"--help") help="true" ;;
-            "-s"|"--sudo") sudo="sudo" ;;
-            *) args+=("$1") ;;
-        esac
-        shift
-    done
-    [[ -z ${args[@]} ]] || set -- "${args[@]}"
-
-    [[ -n $help ]] && ssplus_usage && return 0
-    [[ $# -ne 0 ]] && ssplus_usage && return 1
-
-    while read -r line; do
-        case "$line" in
-            *"Local Address:Port"*)
-                echo -n "$line" | \
-                    sed -r -e "s/ Address:Port/Address/g" \
-                    -e "s/ +\$//g" -e "s# +##g"
-                echo "PIDUserCommandLine"
-                continue
-                ;;
-        esac
-
-        pids=($(
-            echo "$line" | sed "s/pid=//g" | \
-            grep -Eos "\([^()]+\)" | cut -d "," -f 2
-        ))
-
-        if [[ ${#pids[@]} -eq 0 ]]; then
-            echo -n "$line" | sed -r -e "s/users:.*//g" \
-                -e "s/ +\$//g" -e "s/ +//g"
-            echo "-"
-        else
-            for pid in "${pids[@]}"; do
-                echo -n "$line" | sed -r -e "s/users:.*//g" \
-                    -e "s/ +\$//g" -e "s/ +//g"
-                echo -n "$pid"
-                username="$(ps -o user= --pid $pid)"
-                cmd="$(ps -o cmd= --pid $pid)"
-                echo "$username$cmd"
-            done
-        fi
-    done < <($sudo ss -anptu) | column -s "" -t
-
-    ssplus_cleanup
+EOF
+    exit "$1"
 }
 
-if [[ -n ${BASH_SOURCE[0]} ]]; then
-    case "$0" in
-        *"bash") ;;
-        *) ssplus "$@" ;;
+declare -a args deps
+unset help sudo
+color="true"
+deps+=("column")
+deps+=("grep")
+deps+=("ss")
+
+case "$(uname -s)" in
+    "Darwin") errx 2 "Unsupported OS!" ;;
+esac
+
+# Check for missing dependencies
+check_deps
+
+# Parse command line options
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        "--") shift && args+=("$@") && break ;;
+        "-h"|"--help") help="true" ;;
+        "--no-color") unset color ;;
+        "-s"|"--sudo") sudo="sudo" ;;
+        *) args+=("$1") ;;
     esac
-fi
+    shift
+done
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
+
+# Check for valid params
+[[ -z $help ]] || usage 0
+[[ $# -eq 0 ]] || usage 1
+
+while read -r line; do
+    case "$line" in
+        *"Local Address:Port"*)
+            echo -n "$line" | \
+                sed -r -e "s/ Address:Port/Address/g" \
+                -e "s/ +\$//g" -e "s# +##g"
+            echo "PIDUserCommandLine"
+            continue
+            ;;
+    esac
+
+    pids=($(echo "$line" | grep -ioPs ",pid\=\K\d+"))
+
+    if [[ ${#pids[@]} -eq 0 ]]; then
+        echo -n "$line" | sed -r -e "s/users:.*//g" \
+            -e "s/ +\$//g" -e "s/ +//g"
+        echo "-"
+    else
+        for pid in "${pids[@]}"; do
+            echo -n "$line" | sed -r -e "s/users:.*//g" \
+                -e "s/ +\$//g" -e "s/ +//g"
+            [[ -n $sudo ]] || echo -n "-"
+            echo -n "$pid"
+            username="$(ps -o user= --pid $pid)"
+            cmd="$(ps -o cmd= --pid $pid)"
+            echo "$username$cmd"
+        done
+    fi
+done < <($sudo ss -anptu) | column -s "" -t; unset line
diff --git a/security/syscheck b/security/syscheck
--- a/security/syscheck
+++ b/security/syscheck
@@ -3,15 +3,23 @@
 # My own version of checksec.sh
 
 ### Helpers begin
-checkdeps() {
+check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v $d) ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
@@ -21,8 +29,8 @@ long_opt() {
     echo "$arg"
     return $shift
 }
-subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
 ### Helpers end
 
 check_bin() {
@@ -243,19 +251,20 @@ print_output() {
 }
 
 usage() {
-    echo "Usage: ${0##*/} [OPTIONS] <elfbin/dir>...[elfbin/dir]"
-    echo
-    echo "Evaluate the security posture of the system"
-    echo
-    echo "Options:"
-    echo "    -h, --help      Display this help message"
-    echo "    -k, --kernel    Check the kernel config"
-    echo "    --nocolor       Don't use color when displaying output"
-    echo "    -p, --procs     Using running processes as input"
-    echo "    -w, --wide      Use wide output to reduce number of"
-    echo "                    output lines"
-    echo
-    exit $1
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] <elfbin/dir>... [elfbin/dir]
+
+Evaluate the security posture of the system.
+
+Options:
+    -h, --help      Display this help message
+    -k, --kernel    Check the kernel config
+    --no-color      Disable colorized output
+    -p, --procs     Using running processes as input
+    -w, --wide      Use wide output to reduce number of output lines
+
+EOF
+    exit "$1"
 }
 
 declare -a args deps
@@ -271,7 +280,7 @@ shieldrand="$(cat /proc/sys/kernel/exec-shield-randomize 2>/dev/null)"
 [[ -z $shieldrand ]] || ((shieldrand += 3))
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -279,14 +288,14 @@ while [[ $# -gt 0 ]]; do
         "--") shift && args+=("$@") && break ;;
         "-h"|"--help") help="true" ;;
         "-k"|"--kernel") kernel="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-p"|"--procs") procs="true" ;;
         "-w"|"--wide") wide="true" ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
 # Check for valid params
 [[ -z $help ]] || usage 0
