More script updates for newest template

diff --git a/bin/rename_wallpapers b/bin/rename_wallpapers
--- a/bin/rename_wallpapers
+++ b/bin/rename_wallpapers
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
 
 ### Helpers begin
-set -o noglob
-trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
     local missing
     for d in "${deps[@]}"; do
@@ -14,10 +12,30 @@ check_deps() {
             fi
         fi
     done; unset d
-    [[ -z $missing ]] || exit 127
+    [[ -z $missing ]] || exit 128
 }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; clean "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
+
+### Parallel helpers begin
+set -o noglob
+trap "clean 126" SIGINT # Ensure cleanup on ^C
 check_lock() {
-    [[ -n $cache ]] || errx 126 "Cache is not defined"
+    [[ -n $cache ]] || errx 125 "Cache is not defined"
     mkdir -p "$cache"
     if [[ -f "$cache.lock" ]]; then
         errx 125 "$cache.lock already exists"
@@ -58,30 +76,15 @@ clean() {
     show_cursor
     exit "${1:-0}"
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { err "${*:2}"; clean "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 hide_cursor() { echo -en "\e[?25l"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
     if [[ -z $json ]] || [[ ! -f "$json" ]]; then
         return
     fi
     jq -cr ".$*" "$json" | sed -r "s/^null$//g"
 }
-long_opt() {
-    local arg shift="0"
-    case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
-    esac
-    echo "$arg"
-    return $shift
-}
 show_cursor() { echo -en "\e[?25h"; }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
-### Helpers end
+### Parallel helpers end
 
 read_resume_file() {
     echo -n;
@@ -91,9 +94,10 @@ usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTIONS] <img1>... [imgN]
 
-Rename images to MD5_WxH.
+DESCRIPTION
+    Rename images to MD5_WxH.
 
-Options:
+OPTIONS
     -h, --help           Display this help message
     --no-color           Disable colorized output
     -r, --resume         Resume from a previous run
@@ -113,37 +117,46 @@ write_resume_file() {
     echo "{}" >"$json"
 }
 
-declare -a args deps
+declare -a args
 unset help resume verbose
 color="true"
-deps+=("jq")
-deps+=("arTTY")
-deps+=("awk")
-deps+=("grep")
-deps+=("md5sum")
 parallel="true"
 threads="32"
-
-# Check for missing dependencies
-check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
+        "--") shift; args+=("$@"); break ;;
         "-h"|"--help") help="true" ;;
         "--no-color") unset color ;;
         "-r"|"--resume") resume="--resume" ;;
-        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
+        "-t"|"--threads"*) threads="$(long_opt "$@")" ;;
         "-v"|"--verbose") verbose="true" ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
 [[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("jq")
+deps+=("arTTY")
+deps+=("awk")
+deps+=("grep")
+deps+=("md5sum")
+deps+=("sha256sum")
+check_deps
+
+# Check for valid params
 [[ $# -gt 0 ]] || [[ -n $resume ]] || usage 1
 
 # Determine parallel situation
@@ -220,7 +233,6 @@ chmod 700 "$script"
 
 # Run sub-script
 if [[ -n $parallel ]]; then
-    # If more than one dataset, cat and pipe to parallel
     parallel -a "$dataset" --bar --joblog ${resume:++}"$joblog" --lb \
         -P "$threads" -r $resume "$script" {}
     [[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2
