Updated update_repos

diff --git a/bin/update_repos b/bin/update_repos
--- a/bin/update_repos
+++ b/bin/update_repos
@@ -29,23 +29,41 @@
 # --------------------------------------------------------------------
 
 ### Helpers begin
-set -o noglob
-trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
     local missing
     for d in "${deps[@]}"; do
         if [[ -z $(command -v "$d") ]]; then
             # Force absolute path
-            if [[ ! -f "/$d" ]]; then
+            if [[ ! -e "/$d" ]]; then
                 err "$d was not found"
                 missing="true"
             fi
         fi
     done; unset d
-    [[ -z $missing ]] || exit 127
+    [[ -z $missing ]] || exit 128
 }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; clean "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
+
+### Parallel helpers begin
+set -o noglob
+trap "clean 126" SIGINT # Ensure cleanup on ^C
 check_lock() {
-    [[ -n $cache ]] || errx 126 "Cache is not defined"
+    [[ -n $cache ]] || errx 125 "Cache is not defined"
     mkdir -p "$cache"
     if [[ -f "$cache.lock" ]]; then
         errx 125 "$cache.lock already exists"
@@ -86,30 +104,15 @@ clean() {
     show_cursor
     exit "${1:-0}"
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { err "${*:2}"; clean "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 hide_cursor() { echo -en "\e[?25l"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
     if [[ -z $json ]] || [[ ! -f "$json" ]]; then
         return
     fi
     jq -cr ".$*" "$json" | sed -r "s/^null$//g"
 }
-long_opt() {
-    local arg shift="0"
-    case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
-    esac
-    echo "$arg"
-    return $shift
-}
 show_cursor() { echo -en "\e[?25h"; }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
-### Helpers end
+### Parallel helpers end
 
 read_resume_file() { echo -n; }
 
@@ -146,6 +149,7 @@ unset help
 color="true"
 deps+=("git")
 deps+=("jq")
+deps+=("sha256sum")
 parallel="true"
 threads="32"
 
@@ -159,9 +163,14 @@ while [[ $# -gt 0 ]]; do
         "-h"|"--help") help="true" ;;
         "--no-color") unset color ;;
         "-r"|"--resume") resume="--resume" ;;
-        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
+        "-t"|"--threads"*) threads="$(long_opt "$@")" ;;
         "-v"|"--verbose") verbose="true" ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
@@ -180,7 +189,7 @@ fi
 # Cite if needed
 if [[ -n $parallel ]] && [[ ! -f "$HOME/.parallel/will-cite" ]]; then
     pvers="$(parallel --version | grep -ioPs "parallel \K\d+")"
-    if [[ $pvers -lt 20181122 ]]; then
+    if [[ $pvers -gt 20161222 ]] && [[ $pvers -lt 20181122 ]]; then
         mkdir -p "$HOME/.parallel"
         parallel --citation
     fi
