More updates to use new bash templates

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,12 +1,35 @@
 #!/usr/bin/env bash
 
-err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
-
-errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-
-good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }
-
-info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }
+### Helpers begin
+check_deps() {
+    local missing
+    for d in "${deps[@]}"; do
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -e "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
+    done; unset d
+    [[ -z $missing ]] || exit 128
+}
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; exit "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
 
 link() {
     info "Linking directories and files..."
@@ -67,16 +90,6 @@ link_status() {
     done; unset entry
 }
 
-long_opt() {
-    local arg shift="0"
-    case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
-    esac
-    echo "$arg"
-    return $shift
-}
-
 unlink() {
     info "Unlinking directories and files..."
     for entry in "${files[@]}"; do
@@ -108,24 +121,25 @@ unlink() {
 }
 
 usage() {
-    echo "Usage: ${0/*\//} [OPTIONS] <action>"
-    echo "Options:"
-    echo "    -f, --force    Do not make backups"
-    echo "    -h, --help     Display this help message"
-    echo "    --nocolor      Disable colorized output"
-    echo
-    echo "Actions:"
-    echo "    link"
-    echo "        Back up existing scripts and symlink new scripts"
-    echo "    status"
-    echo "        Show what's linked and what isn't"
-    echo "    unlink"
-    echo "        Remove symlinks and restore old scripts"
-    echo
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS] <action>
+
+DESCRIPTION
+     Install scripts from this repo.
+
+OPTIONS
+    -f, --force    Do not make backups
+    -h, --help     Display this help message
+    --no-color     Disable colorized output
+
+ACTIONS
+    link      Back up existing scripts and symlink new scripts
+    status    Show what's linked and what isn't
+    unlink    Remove symlinks and restore old scripts
+
+EOF
     exit $1
 }
-
-warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
 
 declare -a args
 unset force help
@@ -136,18 +150,31 @@ here="$(pwd)"
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
+        "--") shift; args+=("$@"); break ;;
         "-f"|"--force") force="true" ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params and missing dependencies
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("grep")
+deps+=("ln")
+check_deps
+
+# Check for valid params
 [[ $# -eq 1 ]] || usage 1
 
 declare -a files
diff --git a/security/megabuster b/security/megabuster
--- a/security/megabuster
+++ b/security/megabuster
@@ -29,8 +29,6 @@
 # --------------------------------------------------------------------
 
 ### Helpers begin
-set -o noglob
-trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
     local missing
     for d in "${deps[@]}"; do
@@ -42,10 +40,30 @@ check_deps() {
             fi
         fi
     done; unset d
-    [[ -z $missing ]] || exit 127
+    [[ -z $missing ]] || exit 128
 }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; clean "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
+
+### Parallel helpers begin
+set -o noglob
+trap "clean 126" SIGINT # Ensure cleanup on ^C
 check_lock() {
-    [[ -n $cache ]] || errx 126 "Cache is not defined"
+    [[ -n $cache ]] || errx 125 "Cache is not defined"
     mkdir -p "$cache"
     if [[ -f "$cache.lock" ]]; then
         errx 125 "$cache.lock already exists"
@@ -86,30 +104,15 @@ clean() {
     show_cursor
     exit "${1:-0}"
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { err "${*:2}"; clean "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 hide_cursor() { echo -en "\e[?25l"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
     if [[ -z $json ]] || [[ ! -f "$json" ]]; then
         return
     fi
     jq -cr ".$*" "$json" | sed -r "s/^null$//g"
 }
-long_opt() {
-    local arg shift="0"
-    case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
-    esac
-    echo "$arg"
-    return $shift
-}
 show_cursor() { echo -en "\e[?25h"; }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
-### Helpers end
+### Parallel helpers end
 
 cache_default_lists() {
     # Create dcache directory
@@ -637,26 +640,17 @@ read_resume_file() {
     done < <(json_get "wordlists[]"); unset wordlist
 }
 
-# summarize_results() {
-#     [[ -n $summarize ]] || return
-#     [[ -f "$results" ]] || return
-#
-#     info "Summarizing results"
-#     while read -r result; do
-#         good "${result:4}"
-#     done < <(grep -oPs "\[\+\].+" $results | sort -u); unset result
-# }
-
 usage() {
     [[ $1 -ne 0 ]] || logo >&2
     cat <<EOF
 Usage: ${0##*/} [OPTIONS] <host/ip>[:port][/path][?query]
 
-Fuzz paths on a webserver. By default, MegaBuster will try to use the
-directory-list-2.3-medium.txt list from DirBuster and the big.txt and
-common.txt lists from dirb.
+DESCRIPTION
+    Fuzz paths on a webserver. By default, MegaBuster will try to use
+    the directory-list-2.3-medium.txt list from DirBuster and the
+    big.txt and common.txt lists from dirb.
 
-Options:
+OPTIONS
     -a, --apend          Append user specified lists to the default
     -c, --cache          Cache locations of defaults lists
     -f, --force          Assume host is reachable
@@ -707,47 +701,57 @@ $(
 EOF
 }
 
-declare -a args deps ignores wordlists
+declare -a args ignores wordlists
 unset append docache force help proxy resume simulate timeout tls
 unset verbose
 color="true"
 curl="curl -IkLs"
-deps+=("curl")
-deps+=("jq")
-deps+=("parallel")
 threads="32"
-
-# Check for missing dependencies
-check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
+        "--") shift; args+=("$@"); break ;;
         "-a"|"--append") append="true" ;;
         "-c"|"--cache") docache="true" ;;
         "-f"|"--force") force="true" ;;
         "-h"|"--help") help="true" ;;
-        "-i"|"--ignore"*) ignores+=("$(long_opt "$@")*") || shift ;;
-        "-l"|"--list"*) wordlists+=("$(long_opt "$@")") || shift ;;
+        "-i"|"--ignore"*) ignores+=("$(long_opt "$@")*") ;;
+        "-l"|"--list"*) wordlists+=("$(long_opt "$@")") ;;
         "--no-color") unset color ;;
-        "-p"|"--proxy"*) proxy="--proxy $(long_opt "$@")" || shift ;;
+        "-p"|"--proxy"*) proxy="--proxy $(long_opt "$@")" ;;
         "-r"|"--resume") resume="--resume" ;;
         "--simulate") simulate="true" ;;
-        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
-        "--timeout"*) timeout="-m $(long_opt "$@")" || shift ;;
+        "-t"|"--threads"*) threads="$(long_opt "$@")" ;;
+        "--timeout"*) timeout="-m $(long_opt "$@")" ;;
         "--tls") tls="true" ;;
         "-v"|"--verbose") verbose="true" ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
 [[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("awk")
+deps+=("curl")
+deps+=("jq")
+deps+=("parallel")
+deps+=("sha256sum")
+check_deps
+
+# Check for valid params
 [[ $# -le 1 ]] || usage 1
-[[ $# -eq 1 ]] || [[ -n $docache$simulate ]] || usage 1
+[[ $# -eq 1 ]] || [[ -n $docache$resume$simulate ]] || usage 1
 
 # Cite if needed
 if [[ ! -f "$HOME/.parallel/will-cite" ]]; then
@@ -759,11 +763,9 @@ if [[ ! -f "$HOME/.parallel/will-cite" ]]; then
     unset pvers
 fi
 
-# Save host
+# Save command line args
 host="${1:-${simulate:+simulation}}"
-
-# Strip protocol
-host="${host#*://}"
+host="${host#*://}" # Strip protocol
 
 # Cache variables
 hash="$(echo -n "$host" | sha256sum | awk '{print $1}')"
diff --git a/security/shovel b/security/shovel
--- a/security/shovel
+++ b/security/shovel
@@ -29,8 +29,6 @@
 # --------------------------------------------------------------------
 
 ### Helpers begin
-set -o noglob
-trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
     local missing
     for d in "${deps[@]}"; do
@@ -42,10 +40,30 @@ check_deps() {
             fi
         fi
     done; unset d
-    [[ -z $missing ]] || exit 127
+    [[ -z $missing ]] || exit 128
 }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; clean "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
+
+### Parallel helpers begin
+set -o noglob
+trap "clean 126" SIGINT # Ensure cleanup on ^C
 check_lock() {
-    [[ -n $cache ]] || errx 126 "Cache is not defined"
+    [[ -n $cache ]] || errx 125 "Cache is not defined"
     mkdir -p "$cache"
     if [[ -f "$cache.lock" ]]; then
         errx 125 "$cache.lock already exists"
@@ -86,30 +104,15 @@ clean() {
     show_cursor
     exit "${1:-0}"
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { err "${*:2}"; clean "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 hide_cursor() { echo -en "\e[?25l"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
     if [[ -z $json ]] || [[ ! -f "$json" ]]; then
         return
     fi
     jq -cr ".$*" "$json" | sed -r "s/^null$//g"
 }
-long_opt() {
-    local arg shift="0"
-    case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
-    esac
-    echo "$arg"
-    return $shift
-}
 show_cursor() { echo -en "\e[?25h"; }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
-### Helpers end
+### Parallel helpers end
 
 read_resume_file() {
     dns="$(json_get "dns")"
@@ -122,9 +125,10 @@ usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTIONS] [host1]... [hostN]
 
-Identify neighboring hosts in the provided hosts' subnet.
+DESCRIPTION
+    Identify neighboring hosts in the provided hosts' subnet.
 
-Options:
+OPTIONS
     -d, --dns=DNS        Use the specified dns (default: 8.8.8.8)
     -h, --help           Display this help message
     --hosts=FILE         Read hosts from file (ignoring # comments)
@@ -157,9 +161,44 @@ write_resume_file() {
 EOF
 }
 
-declare -a args deps hosts
+declare -a args hosts
 unset file help ping ports resume verbose
 color="true"
+dns="8.8.8.8"
+mask="/24"
+parallel="true"
+threads="32"
+
+# Parse command line options
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        "--") shift; args+=("$@"); break ;;
+        "-d"|"--dns"*) dns="$(long_opt "$@")" ;;
+        "-h"|"--help") help="true" ;;
+        "--hosts"*) file="$(long_opt "$@")" ;;
+        "-i"|"--icmp") ping="true"; unset ports ;;
+        "-m"|"--mask"*) mask="$(long_opt "$@")" ;;
+        "--no-color") unset color ;;
+        "-p"|"--ports"*) unset ping; ports="$(long_opt "$@")" ;;
+        "-r"|"--resume") resume="--resume" ;;
+        "-t"|"--threads"*) threads="$(long_opt "$@")" ;;
+        "-v"|"--verbose") verbose="true" ;;
+        *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
+    esac
+    shift
+done
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
+
+# Help info
+[[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
 deps+=("awk")
 deps+=("dig")
 deps+=("jq")
@@ -168,39 +207,9 @@ deps+=("ping")
 deps+=("sha256sum")
 deps+=("sipcalc")
 deps+=("sort")
-dns="8.8.8.8"
-mask="/24"
-parallel="true"
-threads="32"
-
-# Check for missing dependencies
 check_deps
 
-# Parse command line options
-while [[ $# -gt 0 ]]; do
-    case "$1" in
-        "--") shift && args+=("$@") && break ;;
-        "-d"|"--dns"*) dns="$(long_opt "$@")" || shift ;;
-        "-h"|"--help") help="true" ;;
-        "--hosts"*) file="$(long_opt "$@")" || shift ;;
-        "-i"|"--icmp") ping="true"; unset ports ;;
-        "-m"|"--mask"*) mask="$(long_opt "$@")" || shift ;;
-        "--no-color") unset color ;;
-        "-p"|"--ports"*)
-            unset ping
-            ports="$(long_opt "$@")" || shift
-            ;;
-        "-r"|"--resume") resume="--resume" ;;
-        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
-        "-v"|"--verbose") verbose="true" ;;
-        *) args+=("$1") ;;
-    esac
-    shift
-done
-[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
-
-# Check for valid params
-[[ -z $help ]] || usage 0
+# TODO Check for valid params
 
 # Determine parallel situation
 if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
diff --git a/security/sweeper b/security/sweeper
--- a/security/sweeper
+++ b/security/sweeper
@@ -29,23 +29,41 @@
 # --------------------------------------------------------------------
 
 ### Helpers begin
-set -o noglob
-trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
     local missing
     for d in "${deps[@]}"; do
         if [[ -z $(command -v "$d") ]]; then
             # Force absolute path
-            if [[ ! -f "/$d" ]]; then
+            if [[ ! -e "/$d" ]]; then
                 err "$d was not found"
                 missing="true"
             fi
         fi
     done; unset d
-    [[ -z $missing ]] || exit 127
+    [[ -z $missing ]] || exit 128
 }
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { err "${*:2}"; clean "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+long_opt() {
+    local arg shift="0"
+    case "$1" in
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
+    esac
+    echo "$arg"
+    return $shift
+}
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
+
+### Parallel helpers begin
+set -o noglob
+trap "clean 126" SIGINT # Ensure cleanup on ^C
 check_lock() {
-    [[ -n $cache ]] || errx 126 "Cache is not defined"
+    [[ -n $cache ]] || errx 125 "Cache is not defined"
     mkdir -p "$cache"
     if [[ -f "$cache.lock" ]]; then
         errx 125 "$cache.lock already exists"
@@ -86,30 +104,15 @@ clean() {
     show_cursor
     exit "${1:-0}"
 }
-err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { err "${*:2}"; clean "$1"; }
-good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 hide_cursor() { echo -en "\e[?25l"; }
-info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
     if [[ -z $json ]] || [[ ! -f "$json" ]]; then
         return
     fi
     jq -cr ".$*" "$json" | sed -r "s/^null$//g"
 }
-long_opt() {
-    local arg shift="0"
-    case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
-    esac
-    echo "$arg"
-    return $shift
-}
 show_cursor() { echo -en "\e[?25h"; }
-subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
-warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
-### Helpers end
+### Parallel helpers end
 
 read_resume_file() {
     ping="$(json_get "ping")"
@@ -120,9 +123,10 @@ usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTIONS] [host1]... [hostN]
 
-Sweep a list of hosts and determine if any are up.
+DESCRIPTION
+    Sweep a list of hosts and determine if any are up.
 
-Options:
+OPTIONS
     -h, --help           Display this help message
     --hosts=FILE         Read hosts from file (one per line)
     -i, --icmp           Use ping instead of nping
@@ -151,46 +155,51 @@ write_resume_file() {
 EOF
 }
 
-declare -a args deps
+declare -a args
 unset help hosts ping resume verbose
 color="true"
-deps+=("awk")
-deps+=("jq")
-deps+=("nping")
-deps+=("sha256sum")
 parallel="true"
 ports="22,80,443"
 threads="32"
 
-# Check for missing dependencies
-check_deps
-
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
+        "--") shift; args+=("$@"); break ;;
         "-h"|"--help") help="true" ;;
+        "--hosts"*) hosts="$(long_opt "$@")" ;;
         "-i"|"--icmp") ping="true" ;;
         "--no-color") unset color ;;
-        "-p"|"--ports"*)
-            unset ping
-            ports="$(long_opt "$@")" || shift
-            ;;
+        "-p"|"--ports"*) unset ping; ports="$(long_opt "$@")" ;;
         "-r"|"--resume") resume="--resume" ;;
-        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
-        "--hosts"*) hosts="$(long_opt "$@")" || shift ;;
+        "-t"|"--threads"*) threads="$(long_opt "$@")" ;;
         "-v"|"--verbose") verbose="true" ;;
         *) args+=("$1") ;;
+    esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
     esac
     shift
 done
 [[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("awk")
+deps+=("jq")
+deps+=("nping")
+deps+=("sha256sum")
+check_deps
+
+# Check for valid params
 [[ -n $hosts ]] || [[ $# -gt 0 ]] || usage 1
-[[ -z $hosts ]] || [[ -f $hosts ]] || usage 2
-[[ -n $ports ]] || [[ -n $ping ]] || usage 3
+[[ -z $hosts ]] || [[ -f $hosts ]] || usage 1
+[[ -n $ports ]] || [[ -n $ping ]] || usage 1
 
 # Determine parallel situation
 if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
